language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
services:
- mysql
before_script:
- mysql --user=root --execute='CREATE DATABASE IF NOT EXISTS test;'
- mysql --user=root --execute='GRANT ALL ON test.* TO test@localhost;'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: sxVHHvfv8JMxhPwQNLI+pWEtyxwz39PB4ZXiOZAPBPcSjjHfj0Q1RUesv4KP8Jd/IYcLm1sd5D0KrkuozgSaPeqKVk5QD6iUZZPT7urZX9tQgl0QBcM+giWh094qUCgb1WlU7aqA3grNiAGYctnBFijv3bVy2vzYb7OahrmAjtDQKY1DHPOCfeQv1TKHx8iec8h7XJTIHRWa/SExJ9AM21Ntv2WBcgT+IVES7pcNa67v0or63A8VOJseBAeJuCrAmrJ0KnXSiwyGKPy9jelP6ibCzPAbfBRLgMKFL1OBd85GH4MtakrHqds1UR9NHKGrkVsV6i5VvUZP0TM+8EKob+lgoZI6HBmVSQQAYl9k0PUEaVk32ayhmIfZPrCeCHDk66B4i04ROngW5VPOISSCEs2GnGbRdr+J8P7aaco67wpnBEUrs6y8qPKM9sr+oXft9QBYaxkpQpZBXJssDn33b1miRedu847b22QZ0ojiAc+kblnSps1BlBrodJ4UNsBAfvKgjsS3adf1RtN7uvHItNPNtIU7evLV/JJTkma/E6v+f6izxVC1K3dcnIiRIsEJo1bdPjR9dECwfcHv9GbstNBdKSxwjtb/r5pU9j4Pc4XEh7e7mTDEhbkUyjfXKtSKrUFwE6NE2N8Xl2bwvI1YoEB3MqK8TeLpt9pDQghxwB8=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: tnTglk56QwiMTQ2/xPF+iTb61XCBQq8rrImLK6vBlUYmAyQY7t/dhK/tK60GbWBJZalwbaYOlSJcPCt/Zh7xNUxdWSh2+03WLhtoIK7rycyH/an/r4Hc8CU4SBHQEKH6SGVQExy43UwUqRGNNco1/8G6gC8e3DuXe3ruIEGX69j/nWzKuORPqCSNJyLq1wdzO1iJeTUZ0JF0PUAfrV7nsrk29eGb9IM9R62ENA0kIO5yAciiW0ck7zlkP0oowD5poBKNov7jNuYRXQZsXrcpdeH3gHSo+ZIuXgnAfnJ6Lk1WRTHdMg0GMIGqWj3rP/j7zcjYPFKwZGXuw2nEWtQWyq08EEpgTQvsvusNPVWs3ay1FAJldVExkl7G+SrGfG/hA5dwjgPjwZq2DU4ogRTdf2zU+WmIxF5uahZU3MUDCaOqyjU5UFeuk7UnVKzU8OdSHHU3p2BamYfb21cs0DD66zJfRJJxp4bpiaEfVaiszd10qCoEURE4XK9BFM6I/d8l9Sdl3HsE3cPnC1VUN5fWu9z/gNt6zjapbpMK9Anownu9oXPxunMjP+IeMNljLxZR1EhC9Svbi65B5NBRvNq4HB/qlBzPi/siXFPem8RkqNgQoh7d8Q6tVqHDb2f9caEvRUUhHIClCVUdSIDsoCtHkK5by4hcJ4LiczkDG7Pqy30=
sudo: false
